fix: bug in missing key in data_dict dataframe
Error message:
>>> s.simulate(example_alpha)
2016-03-01: 2162583.39, total: 2162583.39
2016-03-02: 1054879.87, total: 3217463.26
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jerry/Projects/current/worldquant-brain-simulator/src/simulator/simulate.py", line 253, in simulate
    earning = self.get_earning(date, alpha)
  File "/home/jerry/Projects/current/worldquant-brain-simulator/src/simulator/simulate.py", line 260, in get_earning
    self.data_dict[next_day].set_index("symbol")["returns"].loc[alpha.index]
  File "/home/jerry/.pyenv/versions/worldquant-brain/lib/python3.10/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/jerry/.pyenv/versions/worldquant-brain/lib/python3.10/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/jerry/.pyenv/versions/worldquant-brain/lib/python3.10/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/jerry/.pyenv/versions/worldquant-brain/lib/python3.10/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/jerry/.pyenv/versions/worldquant-brain/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/jerry/.pyenv/versions/worldquant-brain/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['MN'] not in index"